apiVersion: batch/v1
kind: Job
metadata:
  name: slog-example
spec:
  template:
    spec:
      containers:
      - name: slog-example
        image: mechiru/slog-example:v0.2.0
        env:
          - name: PROJECT
            value: "your-project-id"
      restartPolicy: OnFailure
